# reference : https://cloud.google.com/build/docs/deploying-builds/deploy-cloud-run?hl=ko
steps:

  # build image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/elevated-dynamo-320013/dedong-web',
        '.'
      ]
    timeout: '300s'

  # push to repository
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'gcr.io/elevated-dynamo-320013/dedong-web'
      ]

  # deploy to cloud run (passive)
  # - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  #   entrypoint: gcloud
  #   args:
  #     [
  #       'run',
  #       'deploy',
  #       'daedong',
  #       '--image',
  #       'gcr.io/elevated-dynamo-320013/dedong-web',
  #       '--region',
  #       'asia-northeast3', # seoul
  #       '--platform',
  #       'managed'
  #    ]

images:
  - 'gcr.io/elevated-dynamo-320013/dedong-web'
